### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [taviso/ctypes.sh#11]
I suggest to reuse a higher level build system than [your current small make file](https://github.com/taviso/ctypes.sh/blob/b4e72ba1a25dbe3e2ce8459b2fe003d6264642ca/Makefile#L1 "Update candidate") so that powerful checks for software features will become easier.
* [CMake](http://cmake.org/ "CMake build system")
* [Autotools](http://www.gnu.org/software/autoconf/#TOCintroduction "GNU build system")

**Comment by joshtriplett** [comment]
If there's some specific "check for software features" you have in mind that this needs to do and isn't doing, please file a bug on that.  Otherwise, there's no particular reason to replace a working makefile.

**Comment by Hunter-Github** [comment]
The makefile isn't working.

**Comment by cemeyer** [comment]
> The makefile isn't working.

Seems fine to me. #9 is a compiler feature support issue on older GCC, not a Makefile issue.

**Comment by taviso** [comment]
Agreed, I should autotool this.

**Comment by elfring** [comment]
* Does [a tool like "autoscan"](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoscan-Invocation.html "Using autoscan to create configure.ac") show any software dependencies that you find worth for further considerations?
* How do you think about to support more development environments by [the reuse of build system generators](http://www.cmake.org/cmake/help/v3.3/manual/cmake-generators.7.html#cmake-generators "Selection for build tool generators")?

**Comment by taviso** [comment]
I can handle autotools, but I don't know CMake very well. I'd accept a pull request though ;-)

**Comment by taviso** [comment]
I've committed a first attempt at adding autoconf support, it's pretty basic right now.

**Comment by taviso** [comment]
automake and libtool support is committed, and seems to be working here.

**Comment by elfring** [comment]
Does [your addition for the build specification](https://github.com/taviso/ctypes.sh/commit/7ca086bd15981d76a36e3e7996b878786189e2ba "Automake and libtool support") need any more fine-tuning?

**Comment by taviso** [comment]
It always needs fine tuning! Please file issues, it's much easier to track if there are bugs reported for each problem.

**Comment by elfring** [comment]
Do my comments for your affected commit need really separate issue numbers?

**Comment by taviso** [comment]
I would find it really helpful, or at least one issue with the comments in.
