### ISSUE TITLE
bsd's and darwin

### ISSUE THREAD

**Issue by rurban** [taviso/ctypes.sh#2]
I'm not asking for mingw or cygwin yet :)
Should not be hard, as libffi does the hard parts.

link.h and RTLD_DEEPBIND are missing on those.
also mempcpy, strchrnul, strndupa

I'm working on that in my non-linux branch https://github.com/rurban/ctypes.sh/tree/non-linux

**Comment by bruno-** [comment]
I think @rurban, said it all.
Just to confirm, I tried to compile on `OSX` and I got:

    ctypes.c:12:10: fatal error: 'link.h' file not found

**Comment by taviso** [comment]
I think I don't need link.h at the moment, I was planning to add a dlinfo command that used link maps, but didn't get around to it. I agree it shouldn't be too hard to get OSX and mingw support, that would be awesome.

**Comment by leto** [comment]
I am also willing to help dev/test this on other machines. Would be awesome to see it cross-platform :+1:

**Comment by cemeyer** [comment]
https://github.com/taviso/ctypes.sh/pull/6  :)

**Comment by Congee** [comment]
thanks for you guys good job :D

**Comment by rurban** [comment]
I'm coming up with a better version based on #6, for Darwin and Windows

**Comment by rurban** [comment]
See #7

**Comment by taviso** [comment]
Does it actually work on Darwin? I'm told Apple build bash incorrectly (they don't export symbols needed for plugins).
