### ISSUE TITLE
Selection of a directory for auxiliary build tools

### ISSUE THREAD

**Issue by elfring** [taviso/ctypes.sh#25]
I suggest to add [the call of the macro "AC_CONFIG_AUX_DIR"](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Input.html#index-AC_005fCONFIG_005fAUX_005fDIR-58 "Storage for auxiliary build tools") to [your configuration script](https://github.com/taviso/ctypes.sh/blob/7ca086bd15981d76a36e3e7996b878786189e2ba/configure.ac#L1 "Automake and libtool support") so that auxiliary build tools will be stored in a dedicated directory.
Would such fine-tuning help a bit for [the issue "Addition of a build system generator"](https://github.com/taviso/ctypes.sh/issues/11#issuecomment-128484621 "Addition of 'configure.ac'")?

**Comment by taviso** [comment]
Nice, that will make things neater. I'll add that.

**Comment by elfring** [comment]
Thanks for [your fine-tuning of the build system](https://github.com/taviso/ctypes.sh/commit/9a15b8573dd2529fa521943e823e4c994cecbece "Use a build-aux directory with autoconf.").
