### ISSUE TITLE
Not clear whether I have a license to use it

### ISSUE THREAD

**Issue by gareth-rees** [taviso/ctypes.sh#3]
This looks awesome, but do I have a license to use it? I looked in [readme.md](https://github.com/taviso/ctypes.sh/blob/master/README.md) and the [Wiki](https://github.com/taviso/ctypes.sh/wiki) but I couldn't see any mention of a license.

**Comment by bruno-** [comment]
MIT-it please! :)
The project is mind blowing.

**Comment by richardmaw-codethink** [comment]
The ISC license is supposed to be good for "do what you want" licenses, permissive without any specific crufty language based on where it came from.

**Comment by taviso** [comment]
Oops. I added a LICENSE file, and went with MIT.

**Comment by gareth-rees** [comment]
MIT licence is perfect, thank you.

**Comment by unphased** [comment]
License file seems to have fell through the cracks? Good to know it's intended as MIT though
