### ISSUE TITLE
No makefile

### ISSUE THREAD

**Issue by Seishinkage** [taviso/ctypes.sh#32]
After running autoconf.sh and configuring, I go to make. With make command I get the following error:

root@Anonymous:~/ctypes.sh# make
make: *** No targets specified and no makefile found.  Stop.

I presume it comes as a result of these two lines at the end of the configure output:

./configure: line 11620: syntax error near unexpected token `FFI,'
./configure: line 11620: `PKG_CHECK_MODULES(FFI, libffi >= 3)'

This leads me to believe that the config file is not locating my installed libffi-dev. Any solution to this?

**Comment by Seishinkage** [comment]
After a few attempts, after cleaning up the config, and running the ./configure for a 6th time, it finally made the makefile as it is supposed to. I have no idea why it wasn't finding libffi-dev. But anyways, you guys might look into this. Not sure if it is a bug in the configuration file or not.

**Comment by taviso** [comment]
That's really odd, if you can reproduce it and paste the configure output and the config.log (and if you ran autogen.sh any output it produced as well) that might help track down what happened.
