### ISSUE TITLE
wget.sh is badly designed

### ISSUE THREAD

**Issue by bontchev** [taviso/ctypes.sh#37]
The test wget.sh tries to connect to Google and checks whether the result is 200 before deciding that the test is passed. That might work in the USA, but where I am (Bulgaria) the result is 302, since the www.google.com tries to redirect me to www.google.bg (which I most definitely _hate_, BTW, but let's not get into that now).

Either make it use a less aggressive site that isn't trying to kick you around depending on your location, or accept a 302 return code as a passed test too.

**Comment by taviso** [comment]
OK, pushed a fix that checks a response was received.
