### ISSUE TITLE
Wondering if you know how to call gtk_init.

### ISSUE THREAD

**Issue by Magicloud** [taviso/ctypes.sh#45]
The sign is `void gtk_init (int *argc, char ***argv)`. Both args are useless to me.
I tried `dlcall gtk_init 'pointer:0x0' 'pointer:0x0'` and got
```
malloc: unknown:0: assertion botched
free: start and end chunk sizes differ
Aborting...
```
Also I tried replace "'pointer:0x0'" with "NULL", I got segmentation fault.

**Comment by taviso** [comment]
Hmm, it works okay for me, which distribution is this?

```
$ dlopen libgtk-3.so.0
0x2425170
$ dlcall gtk_init $NULL $NULL
$ dlcall -r bool gtk_init_check $NULL $NULL
bool:1
```

**Comment by taviso** [comment]
Can you also check if the `gtk.sh` example in the test directory works for you?

Maybe it will give some helpful clue about what's happening.

**Comment by Magicloud** [comment]
Thanks for the help. I found the cause, but do not know why.
I dlopened 'libgtk-3.so', instead of 'libgtk-3.so.0'. Although they are soft links to the same libgtk-3.so.0.2000.8, I added the '.0' suffix, now it works.

**Comment by Magicloud** [comment]
Root cause found. I commented out `taskset -p 1 $$ &> /dev/null`.
