### ISSUE TITLE
Support for musl libc?

### ISSUE THREAD

**Issue by rhencke** [taviso/ctypes.sh#53]
Would you consider support for musl libc?  (or be open to PRs that added support for it?)

(I actually love using ctypes.sh - it's.. actually really good.)

**Comment by cemeyer** [comment]
What doesn't work with musl libc?

**Comment by taviso** [comment]
Would be more than happy to get PRs, or help fix whatever is broken.

**Comment by rhencke** [comment]
Here are some of the things currently preventing compiling against musl.

|Location|Issue|
|---|---|
|https://github.com/taviso/ctypes.sh/blob/091e64421507c3502b38b1b88d78b12b4269e80e/src/struct/dutil.h#L44| no `__always_inline` in musl (could use ` __attribute__ ((__always_inline__))`?)|
|https://github.com/taviso/ctypes.sh/blob/091e64421507c3502b38b1b88d78b12b4269e80e/src/struct/dutil.h#L61|"|
|https://github.com/taviso/ctypes.sh/blob/091e64421507c3502b38b1b88d78b12b4269e80e/src/struct/dutil.h#L75|"|
|https://github.com/taviso/ctypes.sh/blob/091e64421507c3502b38b1b88d78b12b4269e80e/src/struct/dutil.h#L106|"|
|https://github.com/taviso/ctypes.sh/blob/091e64421507c3502b38b1b88d78b12b4269e80e/src/struct/hash.h#L24-L32|no `__WORDSIZE` in musl|
|https://github.com/taviso/ctypes.sh/blob/091e64421507c3502b38b1b88d78b12b4269e80e/src/struct/dwarves_fprintf.c#L1913|no `_SC_LEVEL1_DCACHE_LINESIZE` in musl|

I could start to take a stab at some of these, make a preliminary PR?  I'm sure I'm gonna end up taking you up on that offer for help at some point along the way here.. :)

**Comment by rhencke** [comment]
Closed via https://github.com/taviso/ctypes.sh/commit/6982e6cb226502cb89173fb272b3ef0438e593c4 :)
