### ISSUE TITLE
Does not compile on CentOS 6

### ISSUE THREAD

**Issue by Hunter-Github** [taviso/ctypes.sh#9]
A straightforward `make` gives this:

    cc -std=gnu99 -fPIC -O0 -ggdb3 -Wall -Wextra -fvisibility=hidden -Iinclude -I/usr/lib/libffi-3.0.5/include    -c -o ctypes.o ctypes.c
    ctypes.c: In function ‘rtld_flags_encode’:
    ctypes.c:36: error: nonconstant array index in initializer
    ctypes.c:36: error: (near initialization for ‘flags’)
    ctypes.c:37: error: nonconstant array index in initializer
    ctypes.c:37: error: (near initialization for ‘flags’)
    ctypes.c:38: error: nonconstant array index in initializer
    ctypes.c:38: error: (near initialization for ‘flags’)
    ctypes.c:40: error: nonconstant array index in initializer
    ctypes.c:40: error: (near initialization for ‘flags’)
    ctypes.c:42: error: nonconstant array index in initializer
    ctypes.c:42: error: (near initialization for ‘flags’)
    ctypes.c:43: error: nonconstant array index in initializer
    ctypes.c:43: error: (near initialization for ‘flags’)

glibc version 2.12-1.149
gcc version 4.4.7 20120313 (Red Hat 4.4.7-11)
libffi version 3.0.5 (obviously)

**Comment by taviso** [comment]
Hmm, I guess gcc only recently started allowing that syntax. I'll rewrite it.

I'm afk today, I'll fix this tomorrow.
